setup mailhog containers , api,postgres is added

diff --git a/docker/local/django/entrypoint b/docker/local/django/entrypoint
--- a/docker/local/django/entrypoint
+++ b/docker/local/django/entrypoint
@@ -1,34 +1,41 @@
 #!/bin/bash
 
-#to make it more robust and stop execution if there are errors, pipe failures, or use of undefined variables
 set -o errexit
+
 set -o pipefail
+
 set -o nounset
+
+if [ -z "${POSTGRES_USER}" ]; then
+  base_postgres_image_default_user='postgres'
+  export POSTGRES_USER="${base_postgres_image_default_user}"
+fi
 
 export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
 
-postgres_ready() {
 python << END
 import sys
+import time
 import psycopg2
-try:
-   psycopg2.connect(
+suggest_unrecoverable_after = 30
+start = time.time()
+while True:
+  try:
+    psycopg2.connect(
       dbname="${POSTGRES_DB}",
       user="${POSTGRES_USER}",
       password="${POSTGRES_PASSWORD}",
       host="${POSTGRES_HOST}",
       port="${POSTGRES_PORT}",
-   )
-except psycopg2.OperationalError:
-   sys.exit(-1)
-sys.exit(0)
+    )
+    break
+  except psycopg2.OperationalError as error:
+    sys.stderr.write("Waiting for PostgreSQL to become available...\n")
+    if time.time() - start > suggest_unrecoverable_after:
+      sys.stderr.write(" This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))
+  time.sleep(1)
 END
-}
-until postgres_ready; do
->&2 echo "Waiting for PostgreSQL to become available.....:-("
-sleep 1
-done
->&2 echo "PostgreSQL is ready!!!!.....:-)"
 
-#"$@": This is a special shell variable that expands to all the command line arguments passed to the script. The double quotes ensure that each argument is treated as a separate word, even if they contain spaces or special characters
+>&2 echo "PostgreSQL is available"
+
 exec "$@"
